### PR TITLE
support json jsonnet

### LINKED ISSUE #57: Any plans to support json (and jsonnet)?
I want to refer same json file in ecspresso and ecschedule.
Now I translate jsonnet to yaml via jsonnet cli.
Do you plan to suport json and jsonnet format as well as ecspresso ?

Or may I implement it?

### PR DESCRIPTION
**Pull request by mrymam**
close #57 

- suport json and jsonnet ecschedule config file
  - evaluate jsonnet and encode to json
  - load json and yaml 
- add json, jsonnet to README

### CODE REVIEW

**Comment by Songmu** [comment]
Thank you. I think it's good. Just in case, for backward compatibility, please fall back to YAML when the file type cannot be determined from the extension since there may be existing users using configuration files with naming like `ecschedule.cfg`, `.ecschedule` etc.

**Review by Songmu — CHANGES_REQUESTED** [review]
Thank you. I think it's good. Just in case, for backward compatibility, please fall back to YAML when the file type cannot be determined from the extension since there may be existing users using configuration files with naming like `ecschedule.cfg`, `.ecschedule` etc.

**Comment by mrymam** [comment]
Thank you for a review!

I fixed in [4b49c38](https://github.com/Songmu/ecschedule/pull/58/commits/4b49c3842201656a7a90f56a31c270db4257fea2).
I would appreciate your review again.

> Thank you. I think it's good. Just in case, for backward compatibility, please fall back to YAML when the file type cannot be determined from the extension since there may be existing users using configuration files with naming like `ecschedule.cfg`, `.ecschedule` etc.

**Review by Songmu — APPROVED** [review]

**Comment by Songmu** [comment]
Great! Thank you.

**Pull request merged**
